### ISSUE TITLE
Terminating the GLFW context (and closing the native window) SEGFAULTs on Linux with Vulkan/Xlib

### ISSUE THREAD

**Issue by Duckwhale** [RagnarokResearchLab/RagLite#302]
See #245 - not sure what the workaround here is, as there's no way to control the VK instance?

**Comment by Duckwhale** [comment]
FWIW there's also a SEGFAULT in RML's code when trying the VSYNC fix (using any other present mode):

```sh
#0  0x0000000000000000 in  ()
#1  0x000055555680409e in robin_hood::detail::Table<true, 80ul, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::unique_ptr<Rml::Context, Rml::Releaser<Rml::Context> >, robin_hood::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void>, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~Table() ()
#2  0x00007ffff17538a7 in __run_exit_handlers
    (status=1, listp=0x7ffff18f9718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#3  0x00007ffff1753a60 in __GI_exit (status=<optimized out>) at exit.c:139
#4  0x0000555555bc5829 in lj_cf_os_exit ()
#5  0x0000555555b9101b in lj_BC_FUNCC ()
#6  0x0000555555b6d7f9 in modified_os_exit(lua_State*) (m_luaState=0x7ffff7fab380) at Runtime/LuaVirtualMachine.cpp:45
#7  0x0000555555b9101b in lj_BC_FUNCC ()

```

The runtime doesn't currently bind ``Rml::RemoveContext`` so I can't test if that helps, but they should be destroyed on `Rml::Shutdown` anyway so it might be a separate problem. Should probably look into RML as yet another separate issue.
